# 1.7 Introduction to numpy

In [2]:
import numpy as np

## Creating arrays

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [10]:
a= np.array([1,2,3,4,5,6,12])
a

array([ 1,  2,  3,  4,  5,  6, 12])

In [13]:
a[2] = 10

In [14]:
a

array([ 1,  2, 10,  4,  5,  6, 12])

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [19]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [20]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [21]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

## Multi-dimensional arrays

In [22]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [23]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
n=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [31]:
n[2,1]

np.int64(8)

In [30]:
n[0][1]

np.int64(2)

In [32]:
n[0][1]= 20

In [33]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [34]:
n[0]

array([ 1, 20,  3])

In [35]:
n[2]=[1,1,1]

In [36]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [39]:
n[:,1]

array([20,  5,  1])

In [41]:
n[1,:]

array([4, 5, 6])

In [42]:
n[:,2]=[0,1,2]

In [43]:
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

## Randomly generated arrays

In [45]:
np.random.rand(5,2)

array([[0.90891723, 0.0249619 ],
       [0.52283789, 0.12820968],
       [0.64240439, 0.80413768],
       [0.81534405, 0.97538857],
       [0.98363888, 0.49715151]])

In [50]:
np.random.rand(5,2)

array([[0.62113383, 0.52914209],
       [0.13457995, 0.51357812],
       [0.18443987, 0.78533515],
       [0.85397529, 0.49423684],
       [0.84656149, 0.07964548]])

In [52]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [54]:
np.random.seed(2)
np.random.randn(5,2) #normal distribution

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [55]:
np.random.seed(2)
100*np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [56]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations

In [58]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [59]:
a + 1

array([1, 2, 3, 4, 5])

In [60]:
a*2

array([0, 2, 4, 6, 8])

In [66]:
b=(10+(a*2))**2/100

In [67]:
a +b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [68]:
a * b

array([ 0.  ,  1.44,  3.92,  7.68, 12.96])

In [69]:
a / b

array([0.        , 0.69444444, 1.02040816, 1.171875  , 1.2345679 ])

In [70]:
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

## Compasiron Operations 

In [71]:
a == b

array([False, False, False, False, False])

In [72]:
a >= b

array([False, False,  True,  True,  True])

In [75]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [74]:
a

array([0, 1, 2, 3, 4])

In [73]:
a >=2

array([False, False,  True,  True,  True])

In [77]:
a[a>b] # return a elements for the condition is true

array([2, 3, 4])

## Summarizing operations 

In [83]:
a

array([0, 1, 2, 3, 4])

In [78]:
a.min()

np.int64(0)

In [79]:
a.max()

np.int64(4)

In [82]:
a.sum()

np.int64(10)

In [84]:
a.mean()

np.float64(2.0)

In [85]:
a.std()

np.float64(1.4142135623730951)

In [86]:
n.sum()

np.int64(35)

In [87]:
n.min()

np.int64(0)