In [88]:
import numpy as np

## vector operations

In [93]:
u =np.array([2, 4, 5, 6])

In [92]:
v = np.array([1,0,0,2])

In [94]:
2 * u

array([ 4,  8, 10, 12])

In [95]:
u + v

array([3, 4, 5, 8])

## multiplication

In [96]:
u * v

array([ 2,  0,  0, 12])